### ISSUE TITLE
homework task tracker

### ISSUE THREAD

**Issue by ncvald** [ncvald/Homework-Tracker#2]
This issue tracks the homework tasks assigned. Below is the list of tasks to be completed.

To-Do List
- [x] Set up Overleaf and LaTeX
- [x] Complete Git branching exercises
- [x] Add .EPS figures to the Homework manual
- [x] Submit Homework manual PDF
